from pathlib import Path
p=Path(__file__).resolve().parents[1]/'news/index.html'
s=p.read_text()
old_css=".n-hero{background:linear-gradient(160deg,#1c0a3a 0%,#2b0f5c 55%,#12061f 100%);color:#fff;padding:118px 24px 48px;text-align:center}.n-hero-eyebrow{display:inline-block;font-family:var(--display);font-weight:700;font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.7);margin-bottom:14px}.n-hero h1{font-family:var(--display);font-weight:800;font-size:clamp(2.2rem,6vw,3.4rem);margin-bottom:14px}.n-hero h1 span{color:var(--pink)}.n-hero p{font-size:1.08rem;color:rgba(255,255,255,.75);max-width:590px;margin:auto}"
new_css=".n-hero{position:relative;isolation:isolate;min-height:430px;color:#fff;padding:126px 24px 54px;background:#0d0718 url('/images/news/vegas-dispatch-collage.jpg') center right/cover no-repeat;display:flex;align-items:flex-end}.n-hero:before{content:'';position:absolute;inset:0;z-index:-1;background:linear-gradient(90deg,rgba(9,5,20,.98) 0%,rgba(15,7,30,.91) 34%,rgba(19,8,38,.48) 60%,rgba(10,5,20,.12) 100%)}.n-hero-inner{width:min(1100px,100%);margin:0 auto}.n-hero-eyebrow{display:inline-flex;align-items:center;gap:7px;font-family:var(--display);font-weight:700;font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.78);margin-bottom:14px}.n-hero h1{font-family:var(--display);font-weight:800;font-size:clamp(3rem,7vw,5.3rem);line-height:.96;letter-spacing:-.055em;margin-bottom:18px;max-width:760px}.n-hero h1 span{color:var(--pink)}.n-hero p{font-size:clamp(1rem,2vw,1.18rem);color:rgba(255,255,255,.86);max-width:650px;line-height:1.55}.n-hero-meta{display:flex;align-items:center;gap:12px;margin-top:22px;font-family:var(--display);font-size:.72rem;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:rgba(255,255,255,.76)}.n-hero-meta:before{content:'';width:46px;height:3px;background:linear-gradient(90deg,var(--pink),var(--purple));border-radius:9px}"
if old_css not in s: raise SystemExit('Old hero CSS not found')
s=s.replace(old_css,new_css,1)
s=s.replace("@media(max-width:600px){.articles-grid{grid-template-columns:1fr}.n-hero{padding:92px 20px 36px}","@media(max-width:600px){.articles-grid{grid-template-columns:1fr}.n-hero{min-height:470px;padding:100px 20px 34px;background-position:62% center;align-items:flex-end}.n-hero:before{background:linear-gradient(180deg,rgba(8,5,18,.22) 0%,rgba(12,6,25,.46) 36%,rgba(10,5,20,.96) 78%,#0b0615 100%)}.n-hero h1{font-size:clamp(2.8rem,15vw,4.1rem);max-width:360px}.n-hero p{font-size:.96rem;max-width:390px}.n-hero-meta{margin-top:16px}",1)
old='<header class="n-hero"><span class="n-hero-eyebrow">🌵 Vegas Sidekick</span><h1>Vegas <span>Dispatch</span></h1><p>Las Vegas show news, concert announcements and the stuff worth knowing before you make plans.</p></header>'
new='<header class="n-hero"><div class="n-hero-inner"><span class="n-hero-eyebrow">🌵 Vegas Sidekick</span><h1>Vegas <span>Dispatch</span></h1><p>Las Vegas show news, concert announcements and the stuff worth knowing before you make plans.</p><div class="n-hero-meta">Las Vegas, NV</div></div></header>'
if old not in s: raise SystemExit('Old hero markup not found')
s=s.replace(old,new,1)
# Use the evergreen Dispatch artwork for social sharing too.
s=s.replace('https://vegassidekick.com/images/news/oasis-live-27-las-vegas-wide.jpg','https://vegassidekick.com/images/news/vegas-dispatch-collage.jpg',1)
p.write_text(s)
