from pathlib import Path
import re
p=Path('guides/best-shows-for-first-timers/index.html')
s=p.read_text(encoding='utf-8')
css='''<style id="first-timers-photo-upgrade">.g-hero .wrap{max-width:1180px}.ft-hero-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,.92fr);gap:42px;align-items:center}.ft-hero-copy{min-width:0}.ft-visuals{display:grid;grid-template-columns:1fr 1fr;grid-template-rows:176px 176px;gap:10px;transform:rotate(-1deg)}.ft-shot{position:relative;overflow:hidden;border-radius:18px;border:1px solid rgba(255,255,255,.24);box-shadow:0 18px 50px rgba(0,0,0,.25);background:#261147}.ft-shot:first-child{grid-column:1/3}.ft-shot img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .35s ease}.ft-shot::after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 42%,rgba(13,5,27,.78))}.ft-shot-label{position:absolute;left:12px;bottom:10px;z-index:2;font-family:var(--font-display);font-size:.76rem;font-weight:800;color:#fff}.ft-shot-price{position:absolute;right:10px;top:10px;z-index:2;background:var(--pink);color:#fff;border-radius:999px;padding:5px 9px;font-family:var(--font-display);font-size:.72rem;font-weight:800}.ft-shot:hover img{transform:scale(1.035)}.guide-mini a{padding:0 0 14px;overflow:hidden}.guide-mini a small,.guide-mini a strong,.guide-mini a .mini-detail{margin-left:14px;margin-right:14px}.qa-photo{width:100%;height:112px;object-fit:cover;display:block;margin-bottom:12px}.mini-detail{display:block;font-size:.82rem;color:#5d566a;line-height:1.35;margin-top:5px}@media(max-width:820px){.ft-hero-grid{grid-template-columns:1fr;gap:26px}.ft-visuals{grid-template-rows:148px 148px;transform:none}.g-hero{padding-top:34px}}@media(max-width:520px){.ft-visuals{grid-template-rows:124px 124px;gap:8px}.ft-shot{border-radius:14px}.ft-shot-label{font-size:.66rem}.qa-photo{height:120px}}@media(prefers-reduced-motion:reduce){.ft-shot img{transition:none}.ft-shot:hover img{transform:none}}</style>'''
if 'id="first-timers-photo-upgrade"' not in s: s=s.replace('</head>',css+'\n</head>',1)
hero=re.search(r'<header class="g-hero"><div class="wrap">(.*?)</div></header>',s,re.S)
if not hero: raise SystemExit('hero not found')
inner=hero.group(1)
inner=re.sub(r'\s*<figure class="g-cover">.*?</figure>\s*','',inner,flags=re.S)
visuals='''<div class="ft-visuals" aria-label="Photos of the top three Vegas shows for first-time visitors"><a class="ft-shot" href="/shows/music/vegas-the-show/"><img src="/images/vegas-the-show-hero.webp" alt="VEGAS! The Show at Planet Hollywood"><span class="ft-shot-price">From $63</span><span class="ft-shot-label">#1 VEGAS! The Show</span></a><a class="ft-shot" href="/shows/cirque/o/"><img src="/images/o-hero.jpg" alt="O by Cirque du Soleil at Bellagio"><span class="ft-shot-price">From $156</span><span class="ft-shot-label">#2 O by Cirque du Soleil</span></a><a class="ft-shot" href="/shows/spectaculars/absinthe/"><img src="/images/absinthe-2.webp" alt="Absinthe at Caesars Palace"><span class="ft-shot-price">From $122</span><span class="ft-shot-label">#3 Absinthe</span></a></div>'''
newhero='<header class="g-hero"><div class="wrap"><div class="ft-hero-grid"><div class="ft-hero-copy">'+inner+'</div>'+visuals+'</div></div></header>'
s=s[:hero.start()]+newhero+s[hero.end():]
mini=re.search(r'<div class="guide-mini">.*?</div>',s,re.S)
if not mini: raise SystemExit('quick cards not found')
newmini='''<div class="guide-mini"><a href="/shows/music/vegas-the-show/"><img class="qa-photo" src="/images/vegas-the-show-hero.webp" alt="VEGAS! The Show"><small>My #1 first-trip pick</small><strong>VEGAS! The Show</strong><span class="mini-detail">Saxe Theater · Planet Hollywood · $63</span></a><a href="/shows/cirque/o/"><img class="qa-photo" src="/images/o-hero.jpg" alt="O by Cirque du Soleil"><small>Iconic splurge</small><strong>O by Cirque du Soleil</strong><span class="mini-detail">O Theatre · Bellagio · $156</span></a><a href="/shows/spectaculars/absinthe/"><img class="qa-photo" src="/images/absinthe-2.webp" alt="Absinthe"><small>Adults</small><strong>Absinthe</strong><span class="mini-detail">Spiegeltent · Caesars Palace · $122</span></a></div>'''
s=s[:mini.start()]+newmini+s[mini.end():]
p.write_text(s,encoding='utf-8')
print('First-Timers visual upgrade applied')