from pathlib import Path
p=Path('guides/best-shows-for-first-timers/index.html')
s=p.read_text(encoding='utf-8')
css='''<style id="first-timers-photo-upgrade">\n.g-hero .wrap{max-width:1180px}.ft-hero-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,.92fr);gap:42px;align-items:center}.ft-hero-copy{min-width:0}.ft-visuals{display:grid;grid-template-columns:1fr 1fr;grid-template-rows:176px 176px;gap:10px;transform:rotate(-1deg)}.ft-shot{position:relative;overflow:hidden;border-radius:18px;border:1px solid rgba(255,255,255,.24);box-shadow:0 18px 50px rgba(0,0,0,.25);background:#261147}.ft-shot:first-child{grid-column:1/3}.ft-shot img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .35s ease}.ft-shot::after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 42%,rgba(13,5,27,.78))}.ft-shot-label{position:absolute;left:12px;bottom:10px;z-index:2;font-family:var(--font-display);font-size:.76rem;font-weight:800;color:#fff}.ft-shot-price{position:absolute;right:10px;top:10px;z-index:2;background:var(--pink);color:#fff;border-radius:999px;padding:5px 9px;font-family:var(--font-display);font-size:.72rem;font-weight:800}.ft-shot:hover img{transform:scale(1.035)}.guide-mini a{padding:0 0 14px;overflow:hidden}.guide-mini a small,.guide-mini a strong,.guide-mini a .mini-detail{margin-left:14px;margin-right:14px}.qa-photo{width:100%;height:112px;object-fit:cover;display:block;margin-bottom:12px}.mini-detail{display:block;font-size:.82rem;color:#5d566a;line-height:1.35;margin-top:5px}@media(max-width:820px){.ft-hero-grid{grid-template-columns:1fr;gap:26px}.ft-visuals{grid-template-rows:148px 148px;transform:none}.g-hero{padding-top:34px}}@media(max-width:520px){.ft-visuals{grid-template-rows:124px 124px;gap:8px}.ft-shot{border-radius:14px}.ft-shot-label{font-size:.66rem}.qa-photo{height:120px}}@media(prefers-reduced-motion:reduce){.ft-shot img{transition:none}.ft-shot:hover img{transform:none}}\n</style>'''
if 'id="first-timers-photo-upgrade"' not in s:
    s=s.replace('</head>',css+'\n</head>',1)
old='''<header class="g-hero"><div class="wrap"><span class="g-eyebrow">🌵 First Trip, Sorted</span><h1>The Best Vegas Shows for <span class="accent">First-Timers</span></h1><p class="g-sub">Never been? Start here. The 12 can\'t-miss shows that define a first trip to the Strip — ranked, with the real price.</p><div class="g-meta">'''
new='''<header class="g-hero"><div class="wrap"><div class="ft-hero-grid"><div class="ft-hero-copy"><span class="g-eyebrow">🌵 First Trip, Sorted</span><h1>The Best Vegas Shows for <span class="accent">First-Timers</span></h1><p class="g-sub">Never been? Start here. The 12 can\'t-miss shows that define a first trip to the Strip — ranked, with the real price.</p><div class="g-meta">'''
if old not in s: raise SystemExit('hero start not found')
s=s.replace(old,new,1)
old2='''</div>\n  <figure class="g-cover">\n    <img src="/images/guide-first-timers-cover.jpg" alt="Best Vegas shows for first-timers — a glowing Las Vegas Strip theater marquee with fireworks over the Bellagio and New York-New York" loading="eager" width="1200" height="676">\n  </figure>\n</div></header>'''
new2='''</div></div><div class="ft-visuals" aria-label="Photos of the top three Vegas shows for first-time visitors"><a class="ft-shot" href="/shows/music/vegas-the-show/"><img src="/images/vegas-the-show-hero.webp" alt="VEGAS! The Show at Planet Hollywood"><span class="ft-shot-price">From $63</span><span class="ft-shot-label">#1 VEGAS! The Show</span></a><a class="ft-shot" href="/shows/cirque/o/"><img src="/images/o-hero.jpg" alt="O by Cirque du Soleil at Bellagio"><span class="ft-shot-price">From $156</span><span class="ft-shot-label">#2 O by Cirque du Soleil</span></a><a class="ft-shot" href="/shows/spectaculars/absinthe/"><img src="/images/absinthe-2.webp" alt="Absinthe at Caesars Palace"><span class="ft-shot-price">From $122</span><span class="ft-shot-label">#3 Absinthe</span></a></div></div></div></header>'''
if old2 not in s: raise SystemExit('cover block not found')
s=s.replace(old2,new2,1)
old3='''<div class="guide-mini"><a href="/shows/music/vegas-the-show/"><small>My #1 first-trip pick</small><strong>VEGAS! The Show</strong>Saxe Theater · Planet Hollywood · $63</a><a href="/shows/cirque/o/"><small>Iconic splurge</small><strong>O by Cirque du Soleil</strong>O Theatre · Bellagio · $156</a><a href="/shows/spectaculars/absinthe/"><small>Adults</small><strong>Absinthe</strong>Spiegeltent · Caesars Palace · $122</a></div>'''
new3='''<div class="guide-mini"><a href="/shows/music/vegas-the-show/"><img class="qa-photo" src="/images/vegas-the-show-hero.webp" alt="VEGAS! The Show"><small>My #1 first-trip pick</small><strong>VEGAS! The Show</strong><span class="mini-detail">Saxe Theater · Planet Hollywood · $63</span></a><a href="/shows/cirque/o/"><img class="qa-photo" src="/images/o-hero.jpg" alt="O by Cirque du Soleil"><small>Iconic splurge</small><strong>O by Cirque du Soleil</strong><span class="mini-detail">O Theatre · Bellagio · $156</span></a><a href="/shows/spectaculars/absinthe/"><img class="qa-photo" src="/images/absinthe-2.webp" alt="Absinthe"><small>Adults</small><strong>Absinthe</strong><span class="mini-detail">Spiegeltent · Caesars Palace · $122</span></a></div>'''
if old3 not in s: raise SystemExit('quick cards not found')
s=s.replace(old3,new3,1)
p.write_text(s,encoding='utf-8')
print('First-Timers visual upgrade applied')
# trigger